# Generated by Django 4.0.5 on 2022-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unnes',
            name='additional_descrition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unnes',
            name='description',
            field=models.TextField(default='simple title'),
        ),
        migrations.AddField(
            model_name='unnes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unnes',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
